class CfgRoles {
	class GVAR(AntiTank) {
		displayName = "I: Anti Tank";
		icon = "";
	};
	class GVAR(Autorifleman) {
		displayName = "I: Autorifleman";
		icon = "";
	};
	class GVAR(Engineer) {
		displayName = "II: Engineer";
		icon = "";
	};
	class GVAR(ExplosiveSpecialist) {
		displayName = "III: Explosive Specialist";
		icon = "";
	};
	class GVAR(Grenadier) {
		displayName = "II: Grenadier";
		icon = "";
	};
	class GVAR(HeavyGunner) {
		displayName = "III: Heavy Gunner";
		icon = "";
	};
	class GVAR(Marksman) {
		displayName = "I: Marksman";
		icon = "";
	};
	class GVAR(Medic) {
		displayName = "I: Medic";
		icon = "";
	};
	class GVAR(Operative) {
		displayName = "III: Operative";
		icon = "";
	};
	class GVAR(Repair) {
		displayName = "I: Repair Specialist";
		icon = "";
	};
	class GVAR(Rifleman) {
		displayName = "I: Rifleman";
		icon = "";
	};
	class GVAR(Scout) {
		displayName = "II: Scout";
		icon = "";
	};
	class GVAR(Sharpshooter) {
		displayName = "II: Sharpshooter";
		icon = "";
	};
	class GVAR(Sniper) {
		displayName = "III: Sniper";
		icon = "";
	};
};