// NATO LOADOUTS
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\antitank.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\autorifleman.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\engineer.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\explosivespecialist.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\grenadier.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\heavyantitank.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\heavygunner.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\marksman.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\medic.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\operative.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\rifleman.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\scout.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\sharpshooter.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\nato\sniper.hpp"

// CSAT LOADOUTS
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\antitank.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\autorifleman.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\engineer.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\explosivespecialist.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\grenadier.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\heavyantitank.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\heavygunner.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\marksman.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\medic.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\operative.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\rifleman.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\scout.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\sharpshooter.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\csat\sniper.hpp"

// FIA LOADOUTS
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\fia\antitank.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\fia\autorifleman.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\fia\engineer.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\fia\explosivespecialist.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\fia\grenadier.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\fia\marksman.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\fia\medic.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\fia\rifleman.hpp"
#include "\z\carrierstrike\addons\missions\loadouts\vanilla\fia\sharpshooter.hpp"