// Instances of display
#define IDD_MAIN								0
#define IDD_GAME								1
#define IDD_SINGLE_MISSION						2
#define IDD_OPTIONS								3
#define IDD_CONFIGURE							4
#define IDD_OPTIONS_VIDEO						5
#define IDD_OPTIONS_AUDIO						6
#define IDD_MULTIPLAYER							8
#define IDD_LOAD_AAR							9
#define IDD_MAIN_MAP							12
#define IDD_SAVE								13
#define IDD_END									14
#define IDD_SERVER								17
#define IDD_CLIENT								18
#define IDD_IP_ADDRESS							19
#define IDD_SERVER_SETUP						20
#define IDD_CLIENT_SETUP						21
#define IDD_CLIENT_WAIT							22
#define IDD_CHAT								24
#define IDD_CUSTOM_ARCADE						25
#define IDD_ARCADE_MAP							26
#define IDD_ARCADE_UNIT							27
#define IDD_ARCADE_WAYPOINT 					28
#define IDD_TEMPLATE_SAVE						29
#define IDD_TEMPLATE_LOAD						30
#define IDD_LOGIN								31
#define IDD_INTEL								32
#define IDD_CAMPAIGN							33
#define IDD_CREDITS								34
#define IDD_INTEL_GETREADY						37
#define IDD_ARCADE_GROUP						40
#define IDD_ARCADE_SENSOR						41
#define IDD_NEW_USER							42
#define IDD_CAMPAIGN_LOAD						43
#define IDD_ARCADE_EFFECTS						44
#define IDD_ARCADE_MARKER						45
#define IDD_MISSION								46
#define IDD_INTRO								47
#define IDD_OUTRO								48
#define IDD_INTERRUPT							49
#define IDD_DEBRIEFING							50
#define IDD_SELECT_ISLAND						51
#define IDD_SERVER_GET_READY 					52
#define IDD_CLIENT_GET_READY 					53
#define IDD_INSERT_MARKER						54
#define IDD_VOICE_CHAT							55
#define IDD_DEBUG								56
#define IDD_HINTC								57
#define IDD_MISSION_END							58
#define IDD_SERVER_SIDE							59
#define IDD_CLIENT_SIDE							60
#define IDD_MULTIPLAYER_ROLE 					61
#define IDD_AWARD								62
#define IDD_CHANNEL								63
#define IDD_PASSWORD							64
#define IDD_MP_PLAYERS							65
#define IDD_REVERT								66
#define IDD_PORT								69
#define IDD_MP_SETUP							70
#define IDD_FILTER								71
#define IDD_HINTC_EX							72
#define IDD_SELECT_PROFILE						73
#define IDD_CAMPAIGN_SELECT						74
#define IDD_PROFILE								75
#define IDD_PROFILE_NAME						76
#define IDD_PROFILE_FACE						77
#define IDD_PROFILE_VOICE						78
#define IDD_PROFILE_CONTROLLER		  			79
#define IDD_PROFILE_AUDIO						80
#define IDD_PROFILE_VIDEO						81
#define IDD_PROFILE_LIVE						82
#define IDD_MP_TYPE								83
#define IDD_MP_PASSCODE							84
#define IDD_OPTIMATCH_FILTER					86
#define IDD_QUICKMATCH							87
#define IDD_FRIENDS								88
#define IDD_FRIENDS_OPTIONS						89
#define IDD_XWIZARD_TEMPLATE					90
#define IDD_XWIZARD_INTEL						91
#define IDD_XWIZARD_NAME						92
#define IDD_XWIZARD_ISLAND						93
#define IDD_XWIZARD_WEATHER						94
#define IDD_XWIZARD_TIME						95
#define IDD_XWIZARD_UNIT						96
#define IDD_XWIZARD_MAP							97
#define IDD_XWIZARD_UNIT_SELECT 				98
#define IDD_XWIZARD_UNIT_SELECT_CUSTOM  		99
#define IDD_XWIZARD_WAYPOINT					100
#define IDD_DOWNLOAD_CONTENT					101
#define IDD_DOWNLOAD_CONTENT_DETAILS			102
#define IDD_XPLAYERS							103
#define IDD_XPLAYERS_ACTIONS					104
#define IDD_XPLAYERS_FEEDBACK					105
#define IDD_GEAR								106
#define IDD_EQUIP								555
#define IDD_DOWNLOAD_CONTENT_INSTALL			108
#define IDD_SERVER_SETTINGS						109
#define IDD_SERVER_ADVANCED						110
#define IDD_SERVER_SELECT_PLAYER				112
#define IDD_DEDICATED_SERVER					114
#define IDD_FRIEND_MISSIONS						115
#define IDD_LIVE_STATS							116
#define IDD_LIVE_STATS_BOARD					117
#define IDD_NETWORK_CONDITIONS					118
#define IDD_SEND_VOICE_MAIL						119
#define IDD_RECEIVE_VOICE_MAIL					120
#define IDD_SELECT_ISLAND_NEW					351

#define IDD_EDIT_OBJECT							121
#define IDD_MISSION_LOAD						122
#define IDD_MISSION_SAVE						123

#define IDD_EDIT_DIARY_RECORD					125

#define IDD_SERVER_VOTED						126
#define IDD_DEDICATED_SERVER_SETTINGS			127

#define IDD_MISSION_EDITOR						128

#define IDD_DIARY								129

#define IDD_TEAM_SWITCH							130

#define IDD_CONFIGURE_ACTION					131

#define IDD_HOST_SETTINGS						132

#define IDD_MINIMAP								133
#define IDD_OVERLAY_CREATE						134
#define IDD_OVERLAY_LOAD						135

#define IDD_ESRB								136

#define IDD_MISSION_EDITOR_REALTIME				137

//TODO: Has to be checked by Pete!
#define IDD_EDIT_BRIEFING						138
#define IDD_LIVE								139

#define IDD_LASE								141

#define IDD_LAYER_LOAD							142

#define IDD_CONTROLS							143
#define IDD_INTERRUPT_REVERT					144

#define IDD_PERFORMANCE							145
#define IDD_XWIZARD_PARAMS						146
#define IDD_XWIZARD_PARAMETER					147

#define IDD_CONFIGURE_JOYSTICKS					148
#define IDD_CAPTURE								149
#define IDD_CUSTOMIZE_CONTROLLER				150
#define IDD_GAMEOPTIONS							151

//new editor dialog
#define IDD_ARCADE_MODULES						153
#define IDD_SELECT_SAVE							154
#define IDD_DSINTERFACE							155
#define IDD_ADDON_ACTIONS						156

// PhysX debug window
#define IDD_PHYSX_DEBUG							157

// mod launcher dialog
#define IDD_MOD_LAUNCHER						157
#define IDD_NEW_MOD								158

// joystick schemes mapping dialog
#define IDD_JOYSTICK_SCHEMES					159

//AV Terminal dialog - MUF
#define IDD_AV_TERMINAL							160
//Field Manual
#define IDD_FIELD_MANUAL						162
//Dialogue for controls scheme selection
#define IDD_CONTROLS_SCHEME						163
//Dialogue for choosing layout of mission editor. NOTE: 161-163 are already in use, see A3\Ui_f\hpp\defineResincl.inc
#define IDD_EDITOR_LAYOUT						164
//Dialogue for publishing mission on Steam.
#define IDD_PUBLISH_MISSION						165
//Dialogue for selecting tags for mission on Steam.
#define IDD_PUBLISH_MISSION_TAGS				166
//Dialogue for selecting file from the hard drive
#define IDD_FILE_SELECT_DIALOG					167
//Idd reserved for debriefing					168
#define IDD_DLC_VEHICLEMSGBOX					169
#define IDD_DLC_PURCHASENOTIFICATION			170
#define IDD_BOOTCAMPMSGBOX						171
#define IDD_COMMUNITY_GUIDE						172
#define IDD_SLING_LOAD_ASSISTANT				173
#define IDD_DLC_CONTENTBROWSER					174
#define IDD_MP_SCORE_TABLE						175
#define IDD_CAMPAIGN_MP							176
#define IDD_MP_QUICK_PLAY						177
#define IDD_MP_SERVER_SEARCH					178
#define IDD_MP_SERVER_FOUND						179
#define IDD_KEYMAPMSGBOX						180

// MessageBoxes
#define IDD_MSG_DELETEPLAYER					200
#define IDD_MSG_DELETEGAME						201
#define IDD_MSG_CLEARTEMPLATE					202
#define IDD_MSG_EXITTEMPLATE					203
#define IDD_MSG_LAUNCHGAME						204 // ADDED IN PATCH 1.04

#define IDD_MSG_NEWACCOUNT						205

#define IDD_MSG_FRIENDS_REMOVE					206
#define IDD_MSG_FRIENDS_BLOCK					207
#define IDD_MSG_FRIENDS_INVITE					208

#define IDD_MSG_DELETEMISSION					209

#define IDD_MSG_XONLINE_CONNECTION_FAILED		210
#define IDD_MSG_XONLINE_UPDATE_REQUIRED			211
#define IDD_MSG_XONLINE_SERVER_BUSY				212
#define IDD_MSG_XONLINE_REQUIRED_MSG			213
#define IDD_MSG_XONLINE_RECOMMENDED_MSG			214
#define IDD_MSG_XONLINE_INVALID_USER			215
#define IDD_MSG_XONLINE_WRONG_PASSCODE			216

#define IDD_MSG_CANCEL_SUBSCRIPTION				217
#define IDD_MSG_SUBSCRIBE						218
#define IDD_MSG_PURCHASE						219
#define IDD_MSG_INSTALL_ABORT					220
#define IDD_MSG_INSTALL_RESULT					221

#define IDD_MSG_DECLINE_INVITATION				222
#define IDD_MSG_REVOKE_INVITATION				223
#define IDD_MSG_BLOCK_REQUEST					224
#define IDD_MSG_DECLINE_REQUEST					225
#define IDD_MSG_CANCEL_REQUEST					226
#define IDD_MSG_KICK_OFF						227
#define IDD_MSG_TERMINATE_SESSION				228
#define IDD_MSG_NETWORK_CONDITIONS				229

#define IDD_MSG_STATS_NOT_UPLOADED				230

#define IDD_MSG_LOAD_FAILED						231
#define IDD_MSG_DELETESAVE						232

#define IDD_MSG_DISK_FULL						233

#define IDD_MSG_RESTART_MISSION					234
#define IDD_MSG_SAVE_MISSION					235
#define IDD_MSG_SIGN_OUT						236
#define IDD_MSG_LOAD_MISSION					237
#define IDD_MSG_NEGATIVE_FEEDBACK				238
#define IDD_MSG_PENDING_INVITATION				239
#define IDD_MSG_HOST_SESSION					240
#define IDD_MSG_ROLES_LOST						241
#define IDD_MSG_ACCEPT_INVITATION				242
#define IDD_MSG_MP_PLAYER_COUNT					243
#define IDD_MSG_GAME_JOIN						244
#define IDD_MSG_EDITOR_WIZARD_NONAME_MISSION	245

#define IDD_MSG_RESTART_NEEDED					246

// new editor
#define IDD_MSG_COMMIT_OVERLAY					247
#define IDD_MSG_CLEAR_OVERLAY					248
#define IDD_MSG_LOAD_OVERLAY					249
#define IDD_MSG_EXIT_OVERLAY					250
#define IDD_MSG_CREATE_OVERLAY					251
#define IDD_MSG_CLOSE_OVERLAY					252
#define IDD_MSG_LOAD_AAR						253
#define IDD_MSG_CLEAR_MISSION					254
#define IDD_MSG_RETRY_MISSION					255

#define IDD_MSG_DELETE_DIARY_RECORD				256

// XBOX 360 profile and save messages
#define IDD_MSG_XBOX_NO_SIGN_IN					257
#define IDD_MSG_XBOX_NO_STORAGE					258
#define IDD_MSG_XBOX_STORAGE_CHANGED			259
#define IDD_MSG_XBOX_SAVE_FAILED				260
#define IDD_MSG_XBOX_NO_STORAGE_ON_INVITE		261

#define IDD_OPTIONS_AUDIO_ADJUST_MIC			262

//MUF-MessageBox for restarting mission editor during layout change
#define IDD_MSG_RESTART_EDITOR					263

#define IDD_PROGRESS_MESSAGE					264

//Message box for confirming deleting published mission
#define IDD_MSG_DELETE_STEAM_MISSION			265
//Message box for confirming updating published mission
#define IDD_MSG_UPDATE_STEAM_MISSION			266
//Message box for confirming saving current mission before the publish dialog is opened
#define IDD_MSG_SAVE_MISSION_BEFORE_PUBLISH		267
//Message box for asking user to agree with Battleye licence.
#define IDD_MSG_BATTLEYE_LICENCE				268
#define IDD_MSG_UPNP_ACTIVATION					269
//#define IDD_MSG_ACCOUNT_LOGIN_GUIDE			270 - Reserved

// InGameUI
#define IDD_UNITINFO							300
#define IDD_HINT								301
#define IDD_TASKHINT							302
#define IDD_STANCEINFO							303
#define IDD_AVCAMERA							304
#define IDD_STAMINA_BAR							305

//Custom Info
#define IDD_CUSTOMINFO							310
#define IDD_CUSTOMINFO_MINIMAP					311
#define IDD_CUSTOMINFO_SLA						312
#define IDD_CUSTOMINFO_CREW						313
#define IDD_CUSTOMINFO_SENS						314
#define IDD_CUSTOMINFO_FEEDUAV					315
#define IDD_CUSTOMINFO_FEEDDRIVER				316
#define IDD_CUSTOMINFO_FEEDPRIMARYGUNNER		317
#define IDD_CUSTOMINFO_FEEDCOMMANDER			318
#define IDD_CUSTOMINFO_FEEDMISSILE				319
#define IDD_CUSTOMINFO_MINEDETECT				320

//Curator interface
#define IDD_RSCDISPLAYCURATOR								312
#define IDC_RSCDISPLAYCURATOR_MAINMAP						50
#define IDC_RSCDISPLAYCURATOR_OVERLAY						51
#define IDC_RSCDISPLAYCURATOR_MULTISELECTION				52
#define IDC_RSCDISPLAYCURATOR_MOUSEAREA						53
#define IDC_RSCDISPLAYCURATOR_BACKGROUNDADD					100
#define IDC_RSCDISPLAYCURATOR_BACKGROUNDMODE				101
#define IDC_RSCDISPLAYCURATOR_TITLEADD						102
#define IDC_RSCDISPLAYCURATOR_SUBTITLESIDE					103
#define IDC_RSCDISPLAYCURATOR_BACKGROUNDMODIFY				105
#define IDC_RSCDISPLAYCURATOR_BACKGROUNDMISSION				106
#define IDC_RSCDISPLAYCURATOR_TITLEENTITIES					107
#define IDC_RSCDISPLAYCURATOR_BACKGROUND					109
#define IDC_RSCDISPLAYCURATOR_TITLEMODIFY					110
#define IDC_RSCDISPLAYCURATOR_POINTS						111
#define IDC_RSCDISPLAYCURATOR_POINTSPREVIEW					112
#define IDC_RSCDISPLAYCURATOR_DISPLAYNAME					113
#define IDC_RSCDISPLAYCURATOR_BACKGROUNDMINIMAP				114
#define IDC_RSCDISPLAYCURATOR_TITLEMINIMAP					115
#define IDC_RSCDISPLAYCURATOR_MAP							116
#define IDC_RSCDISPLAYCURATOR_MODEUNITS						150
#define IDC_RSCDISPLAYCURATOR_MODEGROUPS					151
#define IDC_RSCDISPLAYCURATOR_MODEMODULES					152
#define IDC_RSCDISPLAYCURATOR_CURSOR						153
#define IDC_RSCDISPLAYCURATOR_MODEMARKERS					154
#define IDC_RSCDISPLAYCURATOR_SIDEBLUFOR					155
#define IDC_RSCDISPLAYCURATOR_SIDEOPFOR						156
#define IDC_RSCDISPLAYCURATOR_SIDEINDEPENDENT				157
#define IDC_RSCDISPLAYCURATOR_SIDECIVILIAN					158
#define IDC_RSCDISPLAYCURATOR_SIDEEMPTY						159
#define IDC_RSCDISPLAYCURATOR_BACKGROUNDGRADIENT			160
#define IDC_RSCDISPLAYCURATOR_LOGO							161
#define IDC_RSCDISPLAYCURATOR_BACKGROUNDPICTUREMISSION		162
#define IDC_RSCDISPLAYCURATOR_BACKGROUNDPICTUREADD			163
#define IDC_RSCDISPLAYCURATOR_BACKGROUNDPICTUREMODIFY		164
#define IDC_RSCDISPLAYCURATOR_BACKGROUNDPICTUREMINIMAP		165
#define IDC_RSCDISPLAYCURATOR_HIDEADD						166
#define IDC_RSCDISPLAYCURATOR_HIDEMODIFY					167
#define IDC_RSCDISPLAYCURATOR_HIDEMISSION					168
#define IDC_RSCDISPLAYCURATOR_HIDEMINIMAP					169
#define IDC_RSCDISPLAYCURATOR_MODERECENT					170
#define IDC_RSCDISPLAYCURATOR_EDIT0							200
#define IDC_RSCDISPLAYCURATOR_EDIT1							201
#define IDC_RSCDISPLAYCURATOR_EDIT2							202
#define IDC_RSCDISPLAYCURATOR_EDIT3							203
#define IDC_RSCDISPLAYCURATOR_EDIT4							204
#define IDC_RSCDISPLAYCURATOR_TYPE							250
#define IDC_RSCDISPLAYCURATOR_CREATE_UNITS_WEST				270
#define IDC_RSCDISPLAYCURATOR_CREATE_UNITS_EAST				271
#define IDC_RSCDISPLAYCURATOR_CREATE_UNITS_GUER				272
#define IDC_RSCDISPLAYCURATOR_CREATE_UNITS_CIV				273
#define IDC_RSCDISPLAYCURATOR_CREATE_UNITS_EMPTY			274
#define IDC_RSCDISPLAYCURATOR_CREATE_GROUPS_WEST			275
#define IDC_RSCDISPLAYCURATOR_CREATE_GROUPS_EAST			276
#define IDC_RSCDISPLAYCURATOR_CREATE_GROUPS_GUER			277
#define IDC_RSCDISPLAYCURATOR_CREATE_GROUPS_CIV				278
#define IDC_RSCDISPLAYCURATOR_CREATE_GROUPS_EMPTY			279
#define IDC_RSCDISPLAYCURATOR_CREATE_MODULES				280
#define IDC_RSCDISPLAYCURATOR_CREATE_MARKERS				281
#define IDC_RSCDISPLAYCURATOR_CREATE_RECENT					282
#define IDC_RSCDISPLAYCURATOR_ENTITIES						251
#define IDC_RSCDISPLAYCURATOR_XLISTBOX0						258
#define IDC_RSCDISPLAYCURATOR_XLISTBOX1						259
#define IDC_RSCDISPLAYCURATOR_XLISTBOX2						260
#define IDC_RSCDISPLAYCURATOR_XLISTBOX3						261
#define IDC_RSCDISPLAYCURATOR_XLISTBOX4						262
#define IDC_RSCDISPLAYCURATOR_SLIDER0						300
#define IDC_RSCDISPLAYCURATOR_SLIDER1						301
#define IDC_RSCDISPLAYCURATOR_SLIDER2						302
#define IDC_RSCDISPLAYCURATOR_SLIDER3						303
#define IDC_RSCDISPLAYCURATOR_SLIDER4						304
#define IDC_RSCDISPLAYCURATOR_COMBO0						400
#define IDC_RSCDISPLAYCURATOR_COMBO1						401
#define IDC_RSCDISPLAYCURATOR_COMBO2						402
#define IDC_RSCDISPLAYCURATOR_COMBO3						403
#define IDC_RSCDISPLAYCURATOR_COMBO4						404
#define IDC_RSCDISPLAYCURATOR_ADD							450
#define IDC_RSCDISPLAYCURATOR_MODIFY						451
#define IDC_RSCDISPLAYCURATOR_MAIN							452
#define IDC_RSCDISPLAYCURATOR_MISSION						453
#define IDC_RSCDISPLAYCURATOR_MODE							454
#define IDC_RSCDISPLAYCURATOR_MINIMAP						455
#define IDC_RSCDISPLAYCURATOR_MODIFYSTATIC					456
#define IDC_RSCDISPLAYCURATOR_BUTTON0						500
#define IDC_RSCDISPLAYCURATOR_BUTTON1						501
#define IDC_RSCDISPLAYCURATOR_BUTTON2						502
#define IDC_RSCDISPLAYCURATOR_BUTTON3						503
#define IDC_RSCDISPLAYCURATOR_BUTTON4						504

//display3DEN
#define IDD_DISPLAY3DEN										313

#define IDC_DISPLAY3DEN_SCROLLBLOCK_TOP						46
#define IDC_DISPLAY3DEN_SCROLLBLOCK_LEFT					47
#define IDC_DISPLAY3DEN_SCROLLBLOCK_RIGHT					48
#define IDC_DISPLAY3DEN_SCROLLBLOCK_BOTTOM					49

#define IDC_DISPLAY3DEN_MAP									51
#define IDC_DISPLAY3DEN_MOUSEAREA							52
#define IDC_DISPLAY3DEN_MODES								53
#define IDC_DISPLAY3DEN_SIDES								54
#define IDC_DISPLAY3DEN_EDIT								55

#define IDC_DISPLAY3DEN_CREATE_OBJECT_WEST					56
#define IDC_DISPLAY3DEN_CREATE_OBJECT_EAST					57
#define IDC_DISPLAY3DEN_CREATE_OBJECT_GUER					58
#define IDC_DISPLAY3DEN_CREATE_OBJECT_CIV					59
#define IDC_DISPLAY3DEN_CREATE_OBJECT_EMPTY					60

#define IDC_DISPLAY3DEN_CREATE_GROUP_WEST					61
#define IDC_DISPLAY3DEN_CREATE_GROUP_EAST					62
#define IDC_DISPLAY3DEN_CREATE_GROUP_GUER					63
#define IDC_DISPLAY3DEN_CREATE_GROUP_CIV					64
#define IDC_DISPLAY3DEN_CREATE_GROUP_EMPTY					65
#define IDC_DISPLAY3DEN_CREATE_OBJECT_LOGIC					66
#define IDC_DISPLAY3DEN_CREATE_OBJECT_MODULE				67
#define IDC_DISPLAY3DEN_CREATE_TRIGGER						68
#define IDC_DISPLAY3DEN_CREATE_WAYPOINT						6900000
#define IDC_DISPLAY3DEN_CREATE_MARKER_ICON					69
#define IDC_DISPLAY3DEN_CREATE_MARKER_SHAPE					70
#define IDC_DISPLAY3DEN_CREATE_GROUP_CUSTOM					71
#define IDC_DISPLAY3DEN_HISTORY								74

#define IDC_DISPLAY3DEN_MISSIONNAME							76

#define IDC_DISPLAY3DEN_SEARCHEDIT_BUTTON					81
#define IDC_DISPLAY3DEN_SEARCHEDIT							80
#define IDC_DISPLAY3DEN_SEARCHCREATE						82
#define IDC_DISPLAY3DEN_SEARCHCREATE_BUTTON					83

#define IDC_DISPLAY3DEN_EDIT_LAYER							84
#define IDC_DISPLAY3DEN_EDIT_DELETE							85
#define IDC_DISPLAY3DEN_EDIT_LAYER_REMOVE					86
#define IDC_DISPLAY3DEN_NAVIGATION_WIDGET					87
#define IDC_DISPLAY3DEN_EDIT_COLLAPSE_ALL					88
#define IDC_DISPLAY3DEN_EDIT_EXPAND_ALL						89
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_ADD				90
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_EDIT				91
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_DELETE			92
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_PUBLISH			93

#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_GROUP				94
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_NAME				95
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_AUTHOR			96
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_CATEGORY			97
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_SUBCATEGORY		98
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_PICTURE			99
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_PICTURE_EDIT		100
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_OK				101
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_CANCEL			102
#define IDC_DISPLAY3DEN_CUSTOMCOMPOSITION_LIST				103

#define IDC_DISPLAY3DEN_MENUSTRIP 120

// display3DENSave
#define IDD_DISPLAY3DENSAVE									314
#define IDD_OVERRIDE_CHANGES_MSG 							330
#define IDD_DISPLAY3DENSAVE_DELETEFOLDER_BOX 				331
#define IDD_DISPLAY3DENSAVE_IMPORT_ENTITIES 				332

#define IDC_DISPLAY3DENSAVE_FOLDERS							101
#define IDC_DISPLAY3DENSAVE_NAME							102
#define IDC_DISPLAY3DENSAVE_FILES							103
#define IDC_DISPLAY3DENSAVE_TITLE							104
#define IDC_DISPLAY3DENSAVE_SEARCH							105
#define IDC_DISPLAY3DENSAVE_SEARCHBUTTON					106
#define IDC_DISPLAY3DENSAVE_FILTER							107
#define IDC_DISPLAY3DENSAVE_BINARIZETEXT					108
#define IDC_DISPLAY3DENSAVE_BINARIZE						109
#define IDC_DISPLAY3DENSAVE_PURCHASE						110

// display3DENeditComposition
#define IDD_DISPLAY3DENEDITCOMPOSITION						317
#define IDC_DISPLAY3DENEDITCOMPOSITION_NAME					101
#define IDC_DISPLAY3DENEDITCOMPOSITION_AUTHOR				102
#define IDC_DISPLAY3DENEDITCOMPOSITION_CATEGORY				103
#define IDC_DISPLAY3DENEDITCOMPOSITION_SUBCATEGORY			104

// display3DENAttributes
#define IDD_DISPLAY3DENEDITATTRIBUTES						315

#define IDC_DISPLAY3DENEDITATTRIBUTES_TITLE					200
#define IDC_DISPLAY3DENEDITATTRIBUTES_GROUP					201
#define IDC_DISPLAY3DENPYLON_GROUP							2666

#define IDC_DISPLAY3DENEDITATTRIBUTES_TYPE_VALUE			500
#define IDC_DISPLAY3DENEDITATTRIBUTES_TYPE_SEARCH			501
#define IDC_DISPLAY3DENEDITATTRIBUTES_TYPE_SEARCHBUTTON		502

// display3DENNew
#define IDD_DISPLAY3DENNEW									316

#define IDC_DISPLAY3DENNEW_LIST								101
#define IDC_DISPLAY3DENNEW_PURCHASE							107

#define IDC_DISPLAY3DENNEW_TITLE							1000
#define IDC_DISPLAY3DENNEW_NAME								1002
#define IDC_DISPLAY3DENNEW_AUTHOR							1003
#define IDC_DISPLAY3DENNEW_NAMEBACKGROUND					1004
#define IDC_DISPLAY3DENNEW_ISLANDPANORAMA					1200
#define IDC_DISPLAY3DENNEW_INTERLACING						1201
#define IDC_DISPLAY3DENNEW_CLOUD1							1202
#define IDC_DISPLAY3DENNEW_CLOUD2							1203
#define IDC_DISPLAY3DENNEW_CLOUD3							1204
#define IDC_DISPLAY3DENNEW_CLOUD4							1205
#define IDC_DISPLAY3DENNEW_ISLANDGROUP						2300
#define IDC_DISPLAY3DENNEW_BUTTONCONTINUE					2600
#define IDC_DISPLAY3DENNEW_BUTTONCANCEL						2700

#define IDC_DISPLAY3DEN_EDITORPREVIEW_GROUP					98
#define IDC_DISPLAY3DEN_EDITORPREVIEW						99
